# Generated by Django 5.2.6 on 2025-10-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
    ]
